/**
 * @file dukpt_aes256_state_test.c
 *
 * Copyright (c) 2023 Leon Lynch
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program. If not, see
 * <https://www.gnu.org/licenses/>.
 */

#include "dukpt_aes.h"

#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ANSI X9.24-3:2017 Supplement Test Vectors for AES-256 BDK
static const uint8_t bdk[] = {
	0xFE, 0xDC, 0xBA, 0x98, 0x76, 0x54, 0x32, 0x10, 0xF1, 0xF1, 0xF1, 0xF1, 0xF1, 0xF1, 0xF1, 0xF1,
	0xFE, 0xDC, 0xBA, 0x98, 0x76, 0x54, 0x32, 0x10, 0xF1, 0xF1, 0xF1, 0xF1, 0xF1, 0xF1, 0xF1, 0xF1,
};
static const uint8_t ikid[] = { 0x12, 0x34, 0x56, 0x78, 0x90, 0x12, 0x34, 0x56 };
static const uint8_t ik_verify[] = {
	0xCE, 0x9C, 0xE0, 0xC1, 0x01, 0xD1, 0x13, 0x8F, 0x97, 0xFB, 0x6C, 0xAD, 0x4D, 0xF0, 0x45, 0xA7,
	0x08, 0x3D, 0x4E, 0xAE, 0x2D, 0x35, 0xA3, 0x17, 0x89, 0xD0, 0x1C, 0xCF, 0x09, 0x49, 0x55, 0x0F,
};

int main(void)
{
	int r;
	struct dukpt_aes256_state_t state;
	uint8_t ik[DUKPT_AES_KEY_LEN(AES256)];
	uint8_t ksn[DUKPT_AES_KSN_LEN];
	uint8_t txn_key1[DUKPT_AES_KEY_LEN(AES256)];
	uint8_t txn_key2[DUKPT_AES_KEY_LEN(AES256)];

	// Derive Initial Key (IK)
	r = dukpt_aes_derive_ik(bdk, sizeof(bdk), ikid, ik);
	if (r) {
		fprintf(stderr, "dukpt_aes_derive_ik() failed; r=%d\n", r);
		goto exit;
	}
	if (memcmp(ik, ik_verify, sizeof(ik_verify)) != 0) {
		fprintf(stderr, "Initial key derivation is incorrect\n");
		r = 1;
		goto exit;
	}

	// Advance to first KSN
	memcpy(ksn, ikid, DUKPT_AES_IK_ID_LEN);
	memset(ksn + DUKPT_AES_IK_ID_LEN, 0, DUKPT_AES_TC_LEN);
	r = dukpt_aes_ksn_advance(ksn);
	if (r) {
		fprintf(stderr, "dukpt_aes_ksn_advance() failed; r=%d\n", r);
		goto exit;
	}

	// Initialise transaction originating state
	r = dukpt_aes_state_init(ik, sizeof(ik), ikid, &state, sizeof(state));
	if (r) {
		fprintf(stderr, "dukpt_aes_state_init() failed; r=%d\n", r);
		goto exit;
	}
	if (memcmp(state.ksn, ksn, sizeof(ksn)) != 0) {
		fprintf(stderr, "Initial DUKPT state KSN is incorrect\n");
		r = 1;
		goto exit;
	}
	for (size_t i = 0; i < DUKPT_AES_TC_BITS; ++i) {
		if (!state.valid[i]) {
			fprintf(stderr, "Initial DUKPT state valid field is incorrect\n");
			r = 1;
			goto exit;
		}
	}

	// Compare transaction keys generated by transaction originating and
	// transaction receiving implementations for the first 5000000 transactions
	for (size_t i = 0; i < 5000000; ++i) {
		// Transaction key derivation from DUKPT state
		r = dukpt_aes_state_next_txn_key(&state, sizeof(state), txn_key1);
		if (r) {
			if (r == 2 && // Returned by dukpt_aes_ksn_advance() via dukpt_aes_state_next_txn_key()
				dukpt_aes_ksn_is_exhausted(state.ksn) &&
				dukpt_aes_ksn_advance(ksn) == 2
			) {
				// If both implementations agree that the KSN is exhausted,
				// end the test
				break;
			}

			fprintf(stderr, "dukpt_aes_state_next_txn_key() failed; r=%d\n", r);
			goto error;
		}

		// Transaction key derivation from Initial Key (IK)
		r = dukpt_aes_derive_txn_key(ik, sizeof(ik), ksn, txn_key2);
		if (r) {
			fprintf(stderr, "dukpt_aes_derive_txn_key() failed; r=%d\n", r);
			goto error;
		}
		if (memcmp(txn_key1, txn_key2, sizeof(txn_key1)) != 0) {
			fprintf(stderr, "Transaction key derivation %zu is incorrect\n", i);
			r = 1;
			goto error;
		}

		// Advance KSN
		r = dukpt_aes_ksn_advance(ksn);
		if (r) {
			fprintf(stderr, "dukpt_aes_ksn_advance() failed; r=%d\n", r);
			goto error;
		}
		if (memcmp(state.ksn, ksn, sizeof(ksn)) != 0) {
			fprintf(stderr, "KSN mismatch\n");
			r = 1;
			goto error;
		}
	}

	printf("All tests passed.\n");
	r = 0;
	goto exit;

error:
	fprintf(stderr, "KSN: ");
	for (size_t i = 0; i < sizeof(state.ksn); ++i) {
		fprintf(stderr, "%02X", state.ksn[i]);
	}
	fprintf(stderr, "\n");
	fprintf(stderr, "KSN: ");
	for (size_t i = 0; i < sizeof(ksn); ++i) {
		fprintf(stderr, "%02X", ksn[i]);
	}
	fprintf(stderr, "\n");

exit:
	return r;
}
