##############################################################################
# Copyright (c) 2022 Leon Lynch
#
# This file is licensed under the terms of the LGPL v2.1 license.
# See LICENSE file.
##############################################################################

name: MacOS build

on: [push]

env:
  TR31_VERSION: 0.4.4

jobs:
  build-macos-debug:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "MacOS 11", os: macos-11, osx_arch: "x86_64;arm64", build_type: "Debug" }
          - { name: "MacOS 11", os: macos-11, osx_arch: "x86_64;arm64", build_type: "Release" }
          - { name: "MacOS 12", os: macos-12, osx_arch: "x86_64;arm64", build_type: "Debug" }
          - { name: "MacOS 12", os: macos-12, osx_arch: "x86_64;arm64", build_type: "Release" }

    name: ${{ matrix.name }} build (static/${{ matrix.build_type }})
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - run: git describe --always --dirty

    - name: Build TR-31 dependency
      run: |
        gh release download --repo openemv/tr31 ${{ env.TR31_VERSION }}
        tar xvfz tr31-${{ env.TR31_VERSION }}-src.tar.gz
        cd tr31-${{ env.TR31_VERSION }}
        cmake -B build -DCMAKE_OSX_ARCHITECTURES="${{ matrix.osx_arch }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" -DFETCH_MBEDTLS=YES -DBUILD_TR31_TOOL=NO
        cmake --build build
        echo "TR31_DIR=$(pwd)/build/cmake/" >> $GITHUB_ENV
        cd ..
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure CMake
      run: cmake -B build -DCMAKE_OSX_ARCHITECTURES="${{ matrix.osx_arch }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" -DFETCH_MBEDTLS=YES -DFETCH_ARGP=YES -Dtr31_DIR=${{ env.TR31_DIR }}

    - name: Build
      run: cmake --build build

    - name: Test
      run: cmake --build build --target test
