##############################################################################
# Copyright (c) 2022 Leon Lynch
#
# This file is licensed under the terms of the LGPL v2.1 license.
# See LICENSE file.
##############################################################################

name: MacOS build

on: [push]

env:
  TR31_VERSION: 0.4.4

jobs:
  build-macos-debug:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "MacOS 11", os: macos-11, osx_arch: "x86_64;arm64", build_type: "Release", deps: "none", fetch_deps: YES }
          - { name: "MacOS 11", os: macos-11, osx_arch: "x86_64;arm64", build_type: "Debug", deps: "tr31", fetch_deps: YES }
          - { name: "MacOS 11", os: macos-11, osx_arch: "x86_64", build_type: "Release", deps: "tr31", fetch_deps: NO }
          - { name: "MacOS 12", os: macos-12, osx_arch: "x86_64", build_type: "Debug", deps: "tr31", fetch_deps: NO }
          - { name: "MacOS 12", os: macos-12, osx_arch: "x86_64;arm64", build_type: "Release", deps: "tr31", fetch_deps: YES }

    name: ${{ matrix.name }} (${{ matrix.osx_arch }}) build (static/${{ matrix.build_type }}/${{ matrix.deps }})
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies
      # Homebrew doesn't support universal binaries so only install dependencies for x86_64 builds
      if: ${{ matrix.fetch_deps == 'NO' }}
      run: |
        brew install mbedtls@2
        brew install argp-standalone
        echo "MbedTLS_ROOT=$(brew --prefix mbedtls@2)" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - run: git describe --always --dirty

    - name: Build TR-31 dependency
      if: contains(matrix.deps, 'tr31')
      run: |
        gh release download --repo openemv/tr31 ${{ env.TR31_VERSION }}
        tar xvfz tr31-${{ env.TR31_VERSION }}-src.tar.gz
        cd tr31-${{ env.TR31_VERSION }}
        cmake -B build -DCMAKE_OSX_ARCHITECTURES="${{ matrix.osx_arch }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" -DFETCH_MBEDTLS=${{ matrix.fetch_deps }} -DBUILD_TR31_TOOL=NO
        cmake --build build
        echo "TR31_DIR=$(pwd)/build/cmake/" >> $GITHUB_ENV
        echo "CMAKE_REQUIRE_FIND_PACKAGE_tr31=YES" >> $GITHUB_ENV
        cd ..
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure CMake
      run: cmake -B build -DCMAKE_OSX_ARCHITECTURES="${{ matrix.osx_arch }}" -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" -DFETCH_MBEDTLS=${{ matrix.fetch_deps }} -DFETCH_ARGP=${{ matrix.fetch_deps }} -DMbedTLS_ROOT=${{ env.MbedTLS_ROOT }} -Dtr31_DIR=${{ env.TR31_DIR }} -DCMAKE_REQUIRE_FIND_PACKAGE_tr31=${{ env.CMAKE_REQUIRE_FIND_PACKAGE_tr31 }}

    - name: Build
      run: cmake --build build

    - name: Test
      run: cmake --build build --target test
