##############################################################################
# Copyright 2022-2025 Leon Lynch
#
# This file is licensed under the terms of the LGPL v2.1 license.
# See LICENSE file.
##############################################################################

name: Ubuntu build

on: [push]

env:
  TR31_VERSION: 0.6.4

jobs:
  build-ubuntu-debug:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "Ubuntu 22.04", os: ubuntu-22.04, ubuntu_release_name: "jammy", deps: "none", build_dukpt_ui: NO }
          - { name: "Ubuntu 22.04", os: ubuntu-22.04, ubuntu_release_name: "jammy", deps: "tr31/qt", build_dukpt_ui: YES }
          - { name: "Ubuntu 24.04", os: ubuntu-24.04, ubuntu_release_name: "noble", deps: "tr31/qt", build_dukpt_ui: YES }

    name: ${{ matrix.name }} build (static/debug/${{ matrix.deps }})
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install MbedTLS
      run: |
        sudo apt-get update
        sudo apt-get install -y libmbedtls-dev

    - name: Install TR-31 release
      if: contains(matrix.deps, 'tr31')
      run: |
        gh release download --repo openemv/tr31 ${{ env.TR31_VERSION }}
        unzip tr31-${{ env.TR31_VERSION }}-${{ matrix.os }}.zip
        sudo dpkg -i tr31_${{ env.TR31_VERSION }}-0ubuntu1~ppa1~${{ matrix.ubuntu_release_name }}1_amd64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Qt5
      if: contains(matrix.deps, 'qt')
      run: sudo apt-get install -y qtbase5-dev

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - run: git describe --always --dirty

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE="Debug" \
          -DCMAKE_REQUIRE_FIND_PACKAGE_tr31=${{ contains(matrix.deps, 'tr31') && 'YES' || 'NO' }} \
          -DCMAKE_DISABLE_FIND_PACKAGE_Qt5=${{ !contains(matrix.deps, 'qt') && 'YES' || 'NO' }} \
          -DCMAKE_DISABLE_FIND_PACKAGE_Qt6=${{ !contains(matrix.deps, 'qt') && 'YES' || 'NO' }} \
          -DBUILD_DUKPT_UI=${{ matrix.build_dukpt_ui }}

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --test-dir build --output-on-failure

  build-ubuntu-sanitizers:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "Ubuntu 24.04 build (debug/sanitizers)", os: "ubuntu-24.04", ubuntu_release_name: "noble", build_type: "Debug" }
          - { name: "Ubuntu 24.04 build (release/sanitizers)", os: "ubuntu-24.04", ubuntu_release_name: "noble", build_type: "RelWithDebInfo" }

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmbedtls-dev qtbase5-dev

    - name: Install TR-31 release
      run: |
        gh release download --repo openemv/tr31 ${{ env.TR31_VERSION }}
        unzip tr31-${{ env.TR31_VERSION }}-${{ matrix.os }}.zip
        sudo dpkg -i tr31_${{ env.TR31_VERSION }}-0ubuntu1~ppa1~${{ matrix.ubuntu_release_name }}1_amd64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake with sanitizers
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" \
          -DDUKPT_ENABLE_SANITIZERS=ON \
          -DBUILD_DUKPT_UI=YES

    - name: Build
      run: cmake --build build

    - name: Test with sanitizers
      run: ctest --test-dir build --output-on-failure

  build-ubuntu-legacy-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "Ubuntu 20.04", os: ubuntu-20.04, container: "ubuntu:20.04", ubuntu_release_name: "focal" }

    name: ${{ matrix.name }} build (release)
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    steps:
    - name: Prepare container
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y git build-essential cmake file unzip curl gpg
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        apt-get update
        apt-get install -y gh

    - name: Install dependencies
      run: |
        apt-get install -y libmbedtls-dev bash-completion doxygen qtbase5-dev

    - name: Install TR-31 release
      run: |
        gh release download --repo openemv/tr31 ${{ env.TR31_VERSION }}
        unzip tr31-${{ env.TR31_VERSION }}-${{ matrix.os }}.zip
        dpkg -i tr31_${{ env.TR31_VERSION }}-0ubuntu1~ppa1~${{ matrix.ubuntu_release_name }}1_amd64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    # Container user doesn't match runner user
    # Github has only fixed https://github.com/actions/checkout/issues/760
    # not https://github.com/actions/checkout/issues/766
    - name: Configure Git
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git describe --always --dirty

    - name: Get version from git tag
      run: echo "GIT_DESCRIBE=$(git describe --always --dirty)" >> $GITHUB_ENV

    - name: Configure CMake
      # CPACK_DEBIAN_PACKAGE_RELEASE augments the package version for the
      # intended Ubuntu release. The ppa1 component indicates that this is not
      # an official Ubuntu package. The release name component indicates that
      # this is for the specific Ubuntu release that has that name.
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE="RelWithDebInfo" \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DBUILD_SHARED_LIBS=YES \
          -DBUILD_DOCS=YES \
          -DBUILD_DUKPT_UI=YES \
          -DCPACK_COMPONENTS_GROUPING=ALL_COMPONENTS_IN_ONE \
          -DCPACK_DEBIAN_PACKAGE_RELEASE="0ubuntu1~ppa1~${{ matrix.ubuntu_release_name }}1"

    - name: Build
      run: cmake --build build

    - name: Test
      run: cmake --build build --target test

    - name: Package
      run: cmake --build build --target package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dukpt-${{ env.GIT_DESCRIBE }}-${{ matrix.os }}
        path: build/dukpt_*.deb
        if-no-files-found: error

  build-ubuntu-release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "Ubuntu 22.04", os: ubuntu-22.04, ubuntu_release_name: "jammy" }
          - { name: "Ubuntu 24.04", os: ubuntu-24.04, ubuntu_release_name: "noble" }

    name: ${{ matrix.name }} build (release)
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmbedtls-dev doxygen qtbase5-dev

    - name: Install TR-31 release
      run: |
        gh release download --repo openemv/tr31 ${{ env.TR31_VERSION }}
        unzip tr31-${{ env.TR31_VERSION }}-${{ matrix.os }}.zip
        sudo dpkg -i tr31_${{ env.TR31_VERSION }}-0ubuntu1~ppa1~${{ matrix.ubuntu_release_name }}1_amd64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Get version from git tag
      run: echo "GIT_DESCRIBE=$(git describe --always --dirty)" >> $GITHUB_ENV

    - name: Configure CMake
      # CPACK_DEBIAN_PACKAGE_RELEASE augments the package version for the
      # intended Ubuntu release. The ppa1 component indicates that this is not
      # an official Ubuntu package. The release name component indicates that
      # this is for the specific Ubuntu release that has that name.
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE="RelWithDebInfo" \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DBUILD_SHARED_LIBS=YES \
          -DBUILD_DOCS=YES \
          -DBUILD_DUKPT_UI=YES \
          -DCPACK_COMPONENTS_GROUPING=ALL_COMPONENTS_IN_ONE \
          -DCPACK_DEBIAN_PACKAGE_RELEASE="0ubuntu1~ppa1~${{ matrix.ubuntu_release_name }}1"

    - name: Build
      run: cmake --build build

    - name: Test
      run: ctest --test-dir build --output-on-failure

    - name: Package
      run: cmake --build build --target package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dukpt-${{ env.GIT_DESCRIBE }}-${{ matrix.os }}
        path: build/dukpt_*.deb
        if-no-files-found: error
