##############################################################################
# Copyright (c) 2022 Leon Lynch
#
# This file is licensed under the terms of the LGPL v2.1 license.
# See LICENSE file.
##############################################################################

name: Windows build

on: [push]

jobs:
  build-windows-msys2-debug:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw64, env: x86_64, build_type: "Debug" }
          - { sys: mingw64, env: x86_64, build_type: "Release" }
          - { sys: mingw32, env: i686, build_type: "Debug" }
          - { sys: mingw32, env: i686, build_type: "Release" }

    name: Windows MSYS2 ${{matrix.sys}} build (static/${{ matrix.build_type }})

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup MSYS2 ${{matrix.sys}}
      uses: msys2/setup-msys2@v2
      with:
        release: false
        msystem: ${{matrix.sys}}
        install: >-
          base-devel
          mingw-w64-${{matrix.env}}-toolchain
          mingw-w64-${{matrix.env}}-cmake
          mingw-w64-${{matrix.env}}-ninja
          git

    # MSYS2 Git assumes CRLF by default
    - name: Configure Git
      run: |
        git config --global core.autocrlf true
        git describe --always --dirty

    - name: Configure CMake
      run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" -DFETCH_MBEDTLS=YES -DFETCH_ARGP=YES

    - name: Build
      run: cmake --build build

    - name: Test
      run: cmake --build build --target test
